name: Build docs
on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'mchy/library/**'


jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run build script
        run: |
          python ./dev_util/generate_docs.py

      - name: Commit new docs
        run: |
          git status
          git config --global user.name 'Mchy-DP'
          git config --global user.email '129029093+Mchy-DP@users.noreply.github.com'
          git add docs/libs/*
          git commit -m "BOT: Automatic documentation generation [skip ci]"
          git push
