name: Build docs
on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'mchy/library/**'


jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run build script
        run: |
          python ./dev_util/generate_docs.py

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected, committing and pushing..."
          else
            echo "No changes detected, skipping commit and push."
            exit 0
          fi

      - name: Commit new docs
        run: |
          echo "> Config"
          git config --global user.name 'Mchy-DP'
          git config --global user.email '129029093+Mchy-DP@users.noreply.github.com'

          echo "> Adding"
          git status
          git add "docs/libs/*"

          echo "> Committing"
          git status
          git commit -m "BOT: Automatic documentation generation [skip ci]"

          echo "> Pushing"
          git status
          git push
